### PR TITLE
StyleCI config

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I noticed you've signed up for StyleCI. You probably want to disable the psr0 fixer since you're using psr4 here.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Also note you can download the patch styleci provides you and use `git apply` to have your code fixed in seconds. :)

**Comment by fabiofdsantos** [comment]
Thanks!
I'm trying StyleCI :+1:

**Comment by GrahamCampbell** [comment]
Let me know if there's anything else you'd like to see in StyleCI.

**Comment by fabiofdsantos** [comment]
I found the recommended fixers on [Config.php](https://github.com/StyleCI/Config/blob/master/src/Config.php) at [StyleCI/Config](https://github.com/StyleCI/Config/).

I think this should be "more public" so everyone can easily use those fixers before commit something.

**Comment by GrahamCampbell** [comment]
Absolutely, yeh. We will be providing actual documentation at some point. :)

**Pull request merged**
